site_name: 'Luminous Code'
site_description: ''
site_author: 'Yann Duran'
site_url: 'https://luminous-software.solutions/luminous-code'

copyright: 'Copyright (c) 2017 Luminous Software Solutions'

docs_dir: 'docs-source'
site_dir: 'docs'

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'purple'
  custom_dir: 'docs-theme-overrides'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: false

pages:
  - Overview: 'index.md'
  - Getting Started: 'getting-started.md'
  - API Description: 'api.md'
  - Change Log: 'changelog.md'
  - Roadmap: 'roadmap.md'
  - License: 'license.md'

extra:
  links:
    - https://luminous-software.solutions

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: true
