site_name: 'Luminous Code'
site_description: ''
site_author: 'Yann Duran'
site_url: 'https://luminous-software.solutions/luminous-code'

repo_name: 'luminous-code'
repo_url: 'https://github.com/luminous-software/luminous-code'

copyright: 'Copyright (c) 2017 Luminous Software Solutions'

docs_dir: 'docs-source'
site_dir: 'docs'

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'purple'
  custom_dir: 'docs-theme-overrides'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: false

pages:
  - About Luminous Code: 'index.md'
  - How to Get Started: 'getting-started.md'
  - Luminous Code API: 'api.md'
  - Change Log: 'changelog.md'
  - What's Coming: 'roadmap.md'

extra:
  links:
    - https://luminous-software.solutions

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
